-- Applied, and nothing is left in it to run.
--
-- `synced_at`, its trigger on all four tables and the `(user_id, synced_at)`
-- index live in `schema.sql`, which adds the column to tables that already
-- exist and replaces the trigger — so running that file again does everything
-- this migration used to do. The reason the column exists is written there too.
--
-- The file is kept so the numbering of the migrations stays what it was.
